name: Manually Deploy to Heroku

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: "b6490175-f57c-4f5c-b85d-f031726ae6f1"
          heroku_email: "farshadpytthon@gmail.com"
          heroku_app_name: "farshadself2" #Must be unique in Heroku
